config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  resources 'style_surveys'
  namespace :api, defaults: {format: :json} do
    resources :sessions, only: :create
    resources :style_surveys
    # resources :sessions, only: :create, format: false
  end


end

app/models/destination.rb
class Destination < ActiveRecord::Base
  belongs_to :itinerary
  has_many :looks
  accepts_nested_attributes_for :looks

  def self.climates
    [{name: 'rainy', icon: 'icon-rain'}, {name: 'wintery', icon: 'icon-snow' }, {name: 'tropical', icon: 'icon-sun'}]
  end

  def self.purposes
    ['Business', 'Vacation', 'Wedding', 'Other']
  end
end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
  belongs_to :user
  has_many :destinations
  accepts_nested_attributes_for :destinations
end

app/models/look.rb
class Look < ActiveRecord::Base
  belongs_to :destination

  MAX_OUTFITS = 15

  def self.look_items
    ['Jewelry', 'Sunglasses', 'Watch', 'Handbag', 'Shoes', 'Travel Gear', 'Top', 'Bottom', 'Dress', 'Beachwear', 'Suit', 'Outerwear']
  end

  def self.jeans
    ['Boyfriend', 'Flared', 'Skinny', 'High-rise', 'Mid-rise', 'Low-rise', 'Other']
  end

  def self.jewelry
    ['Necklace', 'Earings', 'Bracelet', 'Ring']
  end

  def self.shoes_types
    ['Pumps', 'Wedges', 'Sandals', 'Boots', 'Flats', 'Sneakers', 'I am not sure']
  end
end

app/models/style_survey.rb
class StyleSurvey < ActiveRecord::Base
  belongs_to :user

  def self.style_types
    ['Classic', 'Girly', 'Edgy', 'Casual', 'Preppy', 'Glamorous', 'Trendsetter', 'Business']
  end

  def self.colors
    ['#000000', '#751241', '#e8b379', '#a6a6a6', '#b0c4d8', '#93ab85', '#ddb6b4', '#f71947', '#2fa456', '#0052a4', '#9000c3', '#d80000', '#f77906', '#ffcc00']
  end

  def self.patterns
    ['Lace', 'Stripes', 'Polka-dot', 'Animal', 'Solid']
  end

  def self.brands
    ['Alexander-McQueen', 'Tom-Ford', 'DKNY']
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable
  has_many :style_surveys
  has_many :itineraries
  has_secure_token
end

app/controllers/api/sessions_controller.rb
class Api::SessionsController < ApiController
  def create
    assert_request_content_type Mime::JSON

    respond_to do |format|
      format.json do
        if authenticate_user
          render json: {status: 'success', token: authenticate_user.token}, status: :created
        else
          render json: {status: 'unauthorized'}, status: :unauthorized
        end
      end
    end

  end

  private
  def authenticate_user
    user = User.find_for_database_authentication(email: user_params[:email])
    if user && user.valid_for_authentication? {user.valid_password?(user_params[:password])}
      user.update_attribute(:failed_attempts, 0) unless user.failed_attempts.zero?
      return user
    end
  end

  def assert_request_content_type(content_type)
    raise 'unsupported_media_type' unless request.content_type == content_type
  end

  def user_params
    params.permit(:email, :password)
  end
end

app/controllers/api/style_surveys_controller.rb
class Api::StyleSurveysController < ApiController
  before_action :authenticated?

  def create

  end

  def destroy
    begin
      style_survey = StyleSurvey.find(params[:id])
      style_survey.destroy
      render json: {}, status: :no_content
    rescue ActiveRecord::RecordNotFound
      render json: {}, status: :not_found
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_action :verify_authenticity_token

  protected
  def authenticate_token
    authenticate_or_request_with_http_token do |token, options|
      User.find_by(auth_token: token)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  protected

  def after_confirmation_path_for(resource_name, resource)
    "https://frontend.example.com/login"
  end
end

app/controllers/style_surveys_controller.rb
class StyleSurveysController < ApplicationController
  def new
    @style_survey = StyleSurvey.new
    @destination = Destination.new
    @look = Look.new


  end

  def create
    @style_survey = StyleSurvey.create(style_survey_params)
    @destination = Destination.create(destination_params)
    if @style_survey.save && @destination.save
      flash[:notice] = 'successfully saved'
      redirect_to root_path
    else
      flash[:error] = 'no dice.'
      render :new
    end
  end

  def edit
  end

  def update
  end

  def style_survey_params
    params.require(:style_survey).permit(:style_type, :colors, :patterns, :preferred_brands, :age)
  end

  def destination_params
    params.require(:destination).permit(:name, :climate, :person,  'looks': [:name, :items, :preferred_jeans_types, :preferred_shoes_types, :jewelry_types])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
   def form_group_tag(errors, &block)
     if errors.any?
       content_tag :div, capture(&block), class: 'form-group has-error'
     else
       content_tag :div, capture(&block), class: 'form-group'
     end
   end
 end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/style_surveys_helper.rb
module StyleSurveysHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" style="margin-bottom: 0px;">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= link_to (image_tag 'tripthreads_logo.svg'), root_path, class: 'navbar-brand' %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Get Started' %></li>
        <li><%= link_to 'How It Works' %></li>
        <li><%= link_to 'FAQ' %></li>
        <li><%= link_to 'Log In', new_user_session_path, class: 'btn-login' %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TripThreads</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: 'layouts/navbar' %>
  <% if notice %>
    <p class="notice"><%= notice%></p>
  <% elsif alert %>
    <p class="alert"><%= alert%></p>
  <% end %>
  <%= yield %>

</body>
</html>

app/views/style_surveys/_additional_info.html.erb
<div class="survey-panel" id="additional-info">
  <h2>Anything else we should know?</h2>
  <a href="#get-to-know-you" id="additional-info-next" class="btn btn-warning">Next</a>
</div>

app/views/style_surveys/_age.html.erb
<div class="survey-panel" id="age_section">
  <h2>Don't be shy, let us know how old you are</h2>
  <%= f.text_field :age %>
  <a href="#looks_section" id="age-next" class="btn btn-warning">Next</a>
</div>

app/views/style_surveys/_brands.html.erb
<div class="survey-panel" id="brands_section">
  <h2>Which brands do you prefer?</h2>
  <%= f.text_field :preferred_brands %>
  <a href="#age_section" id="brands-next" class="btn btn-warning">Next</a>
</div>

app/views/style_surveys/_destination.html.erb
<div id="destination_section">
  <h2>Where are you traveling to first?</h2>
  <small>
    Are you traveling to multiple destinations on this upcoming trip?
    If so, we'll make sure to let you add those in too.
  </small>
  <%= fa.text_field :name, class: 'form-control', placeholder: "E.g. Athens, Greece", required: true %>
  <a href="#climate_form" id="destination-next" class="btn btn-warning">Next</a>
</div>

app/views/style_surveys/_get_to_know_you.html.erb
<div class="survey-panel" id="get-to-know-you">
  <h2>We would like to get to know you better</h2>
  <!-- Submit -->
</div>

app/views/style_surveys/_jewelry_color.html.erb
<div class="survey-panel" id="jewelry-color">
  <h2>Which color jewelry do you prefer</h2>
  <a href="#jewelry-pieces" id="jewelry-color-next" class="btn btn-warning">Next</a>
</div>

app/views/style_surveys/_jewelry_pieces.html.erb
<% Look::MAX_OUTFITS.times do |ct| %>
  <div class="survey-panel" id="jewelry-pieces-<%=ct%>">
    <h2>Which jewelry pieces should we include?</h2>
    <a href="#piercings" id="jewelry-pieces-next" class="btn btn-warning">Next</a>
  </div>
<% end %> 

app/views/style_surveys/_look_basics.html.erb
<% Look::MAX_OUTFITS.times do |ct| %>
  <div class="survey-panel" id="look-basics-<%=ct%>">
    <h2><span id="insert-destination"></span> Look #<span id="look-index"></span></h2>
    <h3>This look is for <%= fl.text_field :name, placeholder: 'e.g. "Evening wear for white tie dinner"'%></h3>
    <h3>Day or night?</h3>
    <!-- Radio  -->
    <h3>Day of the week</h3>
    <!-- Radio -->
    <h3>I would like to match the outfit to some clothes of my own image (add image)</h3>
    <!-- Need to build this in -->
    <a href="#look-items" id="looks-basic-next" class="btn btn-warning">Next</a>
  </div>
<% end %>

app/views/style_surveys/_look_items.html.erb
<% Look::MAX_OUTFITS.times do |ct| %>
  <div class="survey-panel" id="look-items-<%=ct%>">
    <h2>Which items would you prefer us to include in your look?</h2>
    <small>Please select up to 5</small>
    <% Look.look_items.each do |l| %>
      <div class="col-lg-3 col-md-3 col-sm-3">
        <%= fl.check_box :items, {multiple: true} %><%= l %>
      </div>
    <% end %>
    <a href="#jeans-types" id="look-items-next" class="btn btn-warning">Next</a>
  </div>
<% end %>

app/views/style_surveys/_no_of_looks.html.erb
<div id="looks_section" class="survey-panel">
  <h2>In <span id="no_looks_header"></span>, how many outfits will you need us to come up with?</h2>
  Great! You'll give us more information for your first outfit here, and we can do the rest later.
  <% Look::MAX_OUTFITS.times do %>
    <%= check_box_tag :outfit_count, 1, false, class: 'outfit_count' %>x
  <% end %>
  <%= fa.hidden_field :number_of_outfits_needed %>
  <a href="#look-basics" id="looks-count-next" class="btn btn-warning">Next</a>

</div>

app/views/style_surveys/_patterns.html.erb
<div class="survey-panel" id="patterns_section">
  <h2>Which patterns do you like?</h2>
  <% StyleSurvey.patterns.each do |ptn| %>
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 pattern_value">
      <%= f.check_box :patterns, {multiple: true}, style: "background-color:#{ptn}", class: 'pattern-circle' %><%= ptn %>
    </div>
  <% end %>
</br>
  <a href="#brands_section" id="patterns-next" class="btn btn-warning">Next</a>
  <%= f.hidden_field :patterns, id: 'colors' %>
</div>

app/views/style_surveys/_piercings.html.erb
<div class="survey-panel" id="piercings">
  <h2>Are your ears pierced?</h2>
  <a href="#additional-info" id="piercings-next" class="btn btn-warning">Next</a>
</div>

app/views/style_surveys/_style_type.html.erb
<div class="survey-panel" id="style_type_section">
  <h2>Which style best describes you?</h2>
  <small>Not finding your exact style type? Simply select the one that matches best
    and you will be able to clarify with your stylist.
  </small>
    <% StyleSurvey.style_types.each do |ss| %>
      <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 style_type_value">
        <%= f.check_box :style_type, {multiple: true}, ss %><%= ss %>
      </div>
    <% end %>
  <%= f.hidden_field :style_type, id: 'style_types' %>
  <a href="#colors_section" id="styles-next" class="btn btn-warning">Next</a>
</div>

app/views/style_surveys/new.html.erb
<div class="centered-form">
  <%= form_for @style_survey do |f| %>

    <!-- Error handling  -->
    <% if @style_survey.errors.any? %>
      <div class="alert alert-danger">
        <h4>There are <%= pluralize(@style_survey.errors.count, "error") %>.</h4>
        <ul>
          <% @style_survey.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <!-- Main form  -->
    <%= fields_for @destination do |fa| %>
      <%= render partial: 'destination', locals: {fa: fa} %>
      <%= render partial: 'climate', locals: {fa: fa} %>
      <%= render partial: 'purpose', locals: {fa: fa} %>
    <% end %>
    <%= render partial: 'style_type', locals: {f: f} %>
    <%= render partial: 'colors', locals: {f: f} %>
    <%= render partial: 'patterns', locals: {f: f} %>
    <%= render partial: 'brands', locals: {f: f} %>
    <%= render partial: 'age', locals: {f: f} %>
    <%= fields_for @destination do |fa| %>
      <%= fa.fields_for @look do |fl| %>
        <%= render partial: 'no_of_looks', locals: {fa: fa} %>
        <!-- Start loop based on No. of looks -->
        <%= render partial: 'look_basics', locals: {fl: fl} %>
        <%= render partial: 'look_items', locals: {fl: fl} %>
        <%= render partial: 'jeans', locals: {fl: fl} %>
        <%= render partial: 'shoes', locals: {fl: fl} %>
        <!-- Move this one -->
        <%= render partial: 'jewelry_color', locals: {f: f} %>
        <!-- ... -->
        <%= render partial: 'jewelry_pieces', locals: {fl: fl} %>
        <!-- End loop -->
        <%= render partial: 'piercings', locals: {f: f} %>
        <%= render partial: 'additional_info', locals: {f: f} %>
        <%= render partial: 'get_to_know_you', locals: {f: f} %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/welcome/_brands_we_offer.html.erb
<div id="home-brands-we-offer-desc" class="content-box centered-div">
  <h2>Featured Brands</h2>
  <div style="margin-top: 30px;">
    <%= image_tag 'alexander-mcqueen.svg', class: 'brands' %>
    <%= image_tag 'celine.svg', class: 'brands' %>
    <%= image_tag 'kate_spade.svg', class: 'brands' %>
    <%= image_tag 'logo-tory-burch.svg', class: 'brands' %>
    <%= image_tag 'logo-dvf.svg', class: 'brands' %>
    <%= image_tag 'rebeccaminkoff.svg', class: 'brands', style: 'width:200px;' %>
  </div>
</div>

app/views/welcome/_footer.html.erb
<div id="footer" class="content-box">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-sm-4 col-xs-4">
        <h4>About Tripthreads</h4>
        <ul>
          <li>About us</li>
          <li>Stylists</li>
        </ul>
      </div>
      <div class="col-md-4 col-sm-4 col-xs-4">
        <h4>Need help?</h4>
        <ul>
          <li>FAQs</li>
          <li>Email help@tripthreads.com</li>
        </ul>
        <small>
          &copy; Tripthreads, <%= DateTime.now.strftime("%Y") %>
        </small>
      </div>
      <div class="col-md-4 col-sm-4 col-xs-4">
        <h4>Follow us!</h4>
        <%= image_tag 'instagram.png', class: 'social'%>
        <%= image_tag 'twitter.png', class: 'social' %>
        <%= image_tag 'pinterest.png', class: 'social' %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/_get_started.html.erb
<div id="get-started" class="content-box">
  <div class="container">
    <div class="row row-eq-height">
      <div class="col-md-6 col-sm-6 col-xs-12">
        <h2>Join Tripthreads</h2>
        <h3>Become a Tripthreads member</h3>
        <ul>
          <li>$200 monthly</li>
          <li>Each month you get up to 5 personalized style ensembles</li>
          <li>Need more looks? or more detailed styling for special occasions?
            Additional ensembles cost $30 per task</li>
        </ul>
        <p>
          All your looks are pre-planned. We keep up with current trends to ensure
          that you’ll look your best at that important business meeting or on the beach.
        </p>
        <button class="btn btn-get-started2">Get Started</button>
      </div>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <div id="membership-card">
          <%= image_tag 'tripthreads_membership_fee.png' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/_how_it_works.html.erb
<div id="home-how-it-works">

</div>
<div id="home-how-it-works-desc" class="content-box centered-div">
  <h2>How It Works</h2>
  <div class="row content">
    <div class="col-sm-4 centered-div">
      <%= image_tag 'itinerary.png', class: 'how-it-works-img' %>
      <p>Hand us your itinerary along with your style, budget, and preference</p>
    </div>
    <div class="col-sm-4 centered-div">
      <%= image_tag 'suit.png', class: 'how-it-works-img' %>
      <p>We review your Profile and send a selection of products to choose from</p>
    </div>
    <div class="col-sm-4 centered-div">
      <%= image_tag 'suitcase.png', class: 'how-it-works-img' %>
      <p>Select what you love, purchase, and pack</p>
    </div>
  </div>
</div>

app/views/welcome/_pricing.html.erb
<div id="pricing" class="content-box centered-div">
  <h2>Pricing</h2>
</div>

app/views/welcome/_what_is.html.erb
<div id="home-header">
  <div class="container">
    <div class="row" style="margin-top:100px;">
      <div class="col-md-6 col-sm-6 col-xs-6">
        <h1 style="text-transform:uppercase; letter-spacing:2px;">We curate looks based on your itinerary</h1>
        <h3 style="color:white; font-family:'Gotham-Thin'">
          Leave it to our expert stylists to create and organize outfits
          whether you are traveling for business or leisure.
        </h3>
        <%= link_to 'Get Started', new_style_survey_path(anchor: 'destination_section'), class: 'btn btn-get-started'%>
      </div>
    </div>
  </div>

</div>
<div id="home-what-is">
  <div class="content-box">
    <h2>What is TripThreads?</h2>
    <p>
      Tripthreads is an easy and instant solution for the jet setter to travel in style, stress free.
      Eliminate the hassle of not knowing what to pack or wear before and after the arrival at your destination.
      Give us your itinerary, budget, and style--we’ll refine and edit your looks.
    </p>
  </div>
</div>

app/views/welcome/index.html.erb
<!-- <h1 style="font-family:'Gotham-Bold';">Welcome#index</h1>
<p style="font-family:'HelveticaNeue-ThinExt'">Find me in app/views/welcome/index.html.erb</p> -->
<%= render partial: 'what_is' %>
<%= render partial: 'how_it_works' %>
<%= render partial: 'brands_we_offer' %>
<%= render partial: 'get_started' %>
<%= render partial: 'footer' %>